### PR TITLE
adding blender 3d asset

### PR DESCRIPTION
**Pull request by gekitsuu**
I know @craSH from a Linux Group I used to be part of. I thought it'd be fun to create a Zoom background for the Neg 9 logo, so I used the .svg file to create a 3D asset in Blender. If you change the render path to match where you want to save this file, you should be able to render a MP4 video file that you can import as a virtual background for most of the video conferencing app. I also have a rendered copy that I'm happy to share, but I wanted to give the 3D asset to you in case you'd like to do something with it in the future.

### CODE REVIEW

**Comment by Javantea** [comment]
I would much prefer a flat file format like obx, stl, or fbx. Blend files are intended to exchange information for every part of blender, which might mean that there is a way to execute arbitrary code by getting someone to open a crafted blend file. While I haven't yet tested this idea, it seems likely.

**Comment by gekitsuu** [comment]
STL files won't capture the materials that I used to color the objects but I'll see how obx or fbx do and modify the pull request

**Comment by gekitsuu** [comment]
I've exported it as an `obj` and `mtl` files. It loses all the animation data, but keeps the materials. The Wikipedia page is [here ](https://en.wikipedia.org/wiki/Wavefront_.obj_file) if you want more info about it.

**Comment by Javantea** [comment]
It looks like you forgot to commit the obj and mtl files. I understand now that it's an animation. Thanks for clearing that up. Thank you for the contribution.

**Comment by gekitsuu** [comment]
Sorry about that, fixed!

**Comment by Javantea** [comment]
I was able to take a look, it looks good. Thanks for your contribution. I'll take a look at the blend file sometime later to see if we can create a file to provide anyone with access to the animation.

**Pull request merged**
